services:
  hub:
    image: ghcr.io/mykola-blonskyi/my-projects:latest
    pull_policy: always
    container_name: hub
    restart: unless-stopped
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST:-true}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OWNER_EMAIL=${OWNER_EMAIL}
      - API_URL=https://blonskyi.dev
    networks:
      - coolify

networks:
  coolify:
    external: true
